### ISSUE TITLE
BLIP2 feature extractor and ITM 

### ISSUE THREAD

**Issue by Bekyilma** [salesforce/LAVIS#126]
Thanks for the great work!
I was trying out BLIP2 feature extractor and ITM. I was wondering if there is a new model_type and name attribute in BLIP 2 for these tasks. It seems the model type and name provided in the notebook examples are not working.
 e.g, `name="blip2_feature_extractor", model_type="pretrain" ` 

I'm getting `AttributeError: 'NoneType' object has no attribute 'from_pretrained' ` error

Thanks.

**Comment by dxli94** [comment]
See the issue and solution here: https://github.com/salesforce/LAVIS/issues/119.

Thanks.

**Comment by Bekyilma** [comment]
Hi, thanks for the quick reply. 

#119 is an encoding issue. I think something is missing in the pre-trained model. 
Currently, I can not load the pre-trained models in the notebook examples. I believe #128 is reporting the same thing.

Thanks!

**Comment by dxli94** [comment]
Hi @Bekyilma,

The key missing warning is expected. See https://github.com/salesforce/LAVIS/issues/128.

Can you elaborate what do you mean by "can not load"? It is throwing exceptions?

**Comment by jonathan-roberts1** [comment]
Hi both,

Great work with this repo, @dxli94!

I might well be wrong but I thought I’d comment in case it helps. 

Have you been using the salesforce-lavis package installed via PYPI (pip install salesforce-lavis)? If so, I think the issue you're having is due to the fact that the stable release v1.0.0 doesn't yet include the blip2_feature_extractor that has been recently added to this repo. If you install the dev version using the instructions in the README you should be able to use the BLIP2 feature extractor.

Thanks

**Comment by dxli94** [comment]
@jonathan-roberts1, thanks a lot for adding this. This is precisely correct. 

We are still actively adding more BLIP2 code at this moment. We will publish a new release once the BLIP2 release is ready.

Thanks.

**Comment by Bekyilma** [comment]
Hi @dxli94,

Yes, the issue was what @jonathan-roberts1 precisely explained. The stable release v1.0.0 doesn't yet include the blip2_feature_extractor. However, I just tried the dev version and I am able to use the feature extractor. 

Thanks again for the great work, Looking forward to future releases!
