### ISSUE TITLE
How to Finetune BLIP2 Captioning Model on custom dataset?

### ISSUE THREAD

**Issue by ECE-Engineer** [salesforce/LAVIS#256]
I'm looking for any resource that will get me the closest to try this. I've had poor luck finding a notebook and/or tutorial on how to finetune the BLIP2 captioning model, so I thought this was the place to ask.

**Comment by dreamlychina** [comment]
> 

me too

**Comment by GMBarra** [comment]
Hello,

I am currently working on a project that requires fine-tuning BLIP2 image caption with a custom dataset. Based on my interpretation of the documentation, the process involves modifying the [captation_builder.py](https://github.com/salesforce/LAVIS/blob/main/lavis/datasets/builders/caption_builder.py) and [coco_captation_dataset.py](https://github.com/salesforce/LAVIS/blob/main/lavis/datasets/datasets/coco_caption_datasets.py) files to include any special conditions for the new dataset. Following this, we can add different transformations to the vis_processor, especially the [blip_processor](https://github.com/salesforce/LAVIS/blob/aff3008b75b64f151d2a3918c0419fc195072008/lavis/processors/blip_processors.py#L104). Finally, we need to adapt our dataset to conform to the standard Coco caption format, or at least that is my current understanding.

Since I just started reading and understanding the documentation for this custom training project, I would appreciate it if a LAVIS developer could confirm or correct any mistakes in my assumptions. Thank you.

**Comment by dxli94** [comment]
@GMBarra Your understanding is correct. Either you can adapt your dataset format, or you create a new dataset builder and dataset class, do which one fits best.

**Comment by JackCai1206** [comment]
Does finetuning BLIP-2 require the frozen vision model and language model to be on the same GPU has the Q-former?

**Comment by shams2023** [comment]
> 你好，
> 
> 我目前正在开发一个项目，需要使用自定义数据集微调 BLIP2 图像标题。根据我对文档的解释，该过程涉及修改[captation_builder.py](https://github.com/salesforce/LAVIS/blob/main/lavis/datasets/builders/caption_builder.py)和[coco_captation_dataset.py](https://github.com/salesforce/LAVIS/blob/main/lavis/datasets/datasets/coco_caption_datasets.py)文件以包含新数据集的任何特殊条件。接下来，我们可以向 vis_processor 添加不同的转换，尤其是[blip_processor](https://github.com/salesforce/LAVIS/blob/aff3008b75b64f151d2a3918c0419fc195072008/lavis/processors/blip_processors.py#L104)。最后，我们需要调整我们的数据集以符合标准的 Coco 字幕格式，或者至少这是我目前的理解。
> 
> 由于我刚刚开始阅读和理解这个自定义培训项目的文档，如果 LAVIS 开发人员能够确认或纠正我的假设中的任何错误，我将不胜感激。谢谢。

Hello!
May I ask if I also want to use BLIP2 for caption operations? How can I achieve this? In the future, Eternal Island's own dataset is also needed for fine-tuning. How can we achieve this?
I need your help, thank you!

**Comment by shams2023** [comment]
> 我正在寻找任何能让我最接近尝试这个的资源。我很不幸地找到了关于如何微调 BLIP2 字幕模型的笔记本和/或教程，所以我认为这是提问的地方。

请问 BLIP2的微调您成功了吗？我希望能在您这获得一些帮助
