### ISSUE TITLE
Generating captions from a heatmap

### ISSUE THREAD

**Issue by pqviet** [salesforce/LAVIS#34]
Congrats on the amazing work!
As related to my research, I want to generate captions of an image from an input heatmap. As stated in the PNP_VQA paper, LAVIS can generate captions based on the relevancy score, but the sample code of the authors (pnp_vqa.ipynb) requires an input question.
How can I do it without the input question?

**Comment by dxli94** [comment]
Hi @pqviet ,

Thanks for your interest.

I am looping in my colleague @anthonytmh , the leading author of PNP-VQA, to answer your question.

Thanks.

**Comment by anthonytmh** [comment]
Hi @pqviet ,

Thanks for your interest. 

The full code is in [lavis/models/pnp_vqa_models](https://github.com/salesforce/LAVIS/blob/main/lavis/models/pnp_vqa_models/pnp_vqa.py).

If you have a predefined heatmap (obtained without an input question), you can pass it as an dictionary entry to `samples` parameter, using `gradcams` as key. See below:
https://github.com/salesforce/LAVIS/blob/187f18023f2e1f466ce0786e39200aef0e3fb6d6/lavis/models/pnp_vqa_models/pnp_vqa.py#L80

The shape of heatmap should be (bsz, num_patches). The `num_patches` is 24*24 since PNP-VQA uses ViT-L/16 with input image size of 384*384. 

You can then call `forward_cap` to obtain the caption.

Thanks.

**Comment by pqviet** [comment]
Thank you for your quick reply.
I will try the code.
