### ISSUE TITLE
Question about PnP

### ISSUE THREAD

**Issue by lonestar234028** [salesforce/LAVIS#80]
Hi, expert:
I'm learning your recent fancy paper, however, I don't know why it is called Fusion in Decoder:
![image](https://user-images.githubusercontent.com/11569402/211192467-890a7f88-974a-41af-8732-31f428771f1c.png)

Can you give me some guidance?

**Comment by lonestar234028** [comment]
In my opinion, it is Fusion in Encoder, which I did not found anywhere.

**Comment by dxli94** [comment]
Hi @lonestar234028, thanks for your interest.

I am looping in my colleague @anthonytmh for help.

Thanks.

**Comment by anthonytmh** [comment]
Hi @lonestar234028, 

It is Fusion-in-Decoder because we encodes each caption with the question separately (no interaction between each captions representation in the encoder) and fuses all the encoded representations as the input to the decoder. We adopt this strategy from Meta Research (Leveraging passage retrieval with generative models for open domain question answering). 

In contrast with Fusion-in-Encoder, all the captions are concatenates into a paragraph as input to the encoder. Please refer to Figure 3 of our paper. 

Thanks.
