### ISSUE TITLE
unfair evaluation of BLIP-2 with Flamingo

### ISSUE THREAD

**Issue by redpandanonthetree** [salesforce/LAVIS#89]
BLIP-2 paper claims "Pre-training data. We use the same pre-training dataset as BLIP with 129M images in total, including COCO (Lin et al., 2014), Visual Genome", where the COCO data is used. The COCO caption data leaks for the zero-shot VQAv2 evaluation (Visual Question Answering). 

So the comparison is unfair compared with Flamingo. The claim "our model outperforms Flamingo80B by 8.7% on zero-shot VQAv2 with 54x fewer trainable parameters" is also not scientifically rigorous.

**Comment by LiJunnan1992** [comment]
The coco-karpathy-train data that we use does not share images with VQA test data. Therefore our comparison with Flamingo (65.0 vs 56.3) is fair.

We appreciate your concern in the pre-training dataset. It is indeed hard to have a "fair" comparison with Flamingo due to their close-sourced pre-training data (which is much larger than what BLIP-2 uses). We are working on further scaling up BLIP-2 with larger-scale web data.

**Comment by redpandanonthetree** [comment]
I am afraid there is a big difference in zero-shot performance. Even if only coco-karpathy-train data was used, the zero-shot test results will be significantly improved. I bet that the results will be worse than Flamingo if the coco captions were removed from your training set.
